export interface RegisterForm {
  name: string;
  email: string;
  password: string;
}

export interface LoginForm {
  email: string;
  password: string;
}

export interface User {
  id?: string;
  name: string;
  email: string;
  password?: string;
}

export interface AuthState {
  isAuthenticated: boolean;
  loading: boolean;
  id: string;
  name: string;
  email: string;
  token: string;
}

// Generated by https://quicktype.io

export interface UserResponse {
  message: string;
  user: User;
  token: string;
}
